### ISSUE TITLE
Error when running grunt

### ISSUE THREAD

**Issue by psuanm5030** [tableau-mkt/generator-web-data-connector#59] opened 2017-06-26 13:25 UTC
Getting a funky error when trying to run grunt on a newly created connector.  Havent really made it very far in this process.  I have not yet modified any of the js code, but was just testing to see if setup was appropriate.

![image](https://user-images.githubusercontent.com/10040269/27541155-dfc6346e-5a50-11e7-9be6-20822fb56a2c.png)

Also adding the npm-debug.log file.  
[npm-debug.txt](https://github.com/tableau-mkt/generator-web-data-connector/files/1102226/npm-debug.txt)

Here was initial setup: 
![image](https://user-images.githubusercontent.com/10040269/27541279-5a6bff96-5a51-11e7-8bfb-fc3a503b1344.png)

**Comment by psuanm5030** [comment] 2017-06-26 13:29
I can use "grunt --force" to load the server and it seems to be working okay.  Thoughts?

**Comment by psuanm5030** [comment] 2017-06-26 13:43
PS - would you mind sharing a completed main.js file?  I am trying to learn... Thats priority, but also trying to build a simple connector to rescuetime.com which is a fairly straightforward API (https://www.rescuetime.com/anapi/setup/documentation).

**Comment by psuanm5030** [comment] 2017-06-26 15:30
Also, missing the all.min.js file in the /build directory.  I have a feeling this is related to the previous errors?

![image](https://user-images.githubusercontent.com/10040269/27547096-dcf06838-5a62-11e7-85bf-c2d95c8a4d77.png)

**Comment by psuanm5030** [comment] 2017-06-26 16:01
One more screen as I continue to see if I can diagnose... These are errors / warnings during the initial yo generation phase.  Maybe I have some work to do, in terms of ensuring the appropriate items are installed / updated? 

![image](https://user-images.githubusercontent.com/10040269/27548445-f6447e2e-5a66-11e7-90a9-c98bb9890d3d.png)
![image](https://user-images.githubusercontent.com/10040269/27548463-01d451a6-5a67-11e7-8572-920d423a1f87.png)
![image](https://user-images.githubusercontent.com/10040269/27548503-1fbf44aa-5a67-11e7-8352-334daef8bed6.png)

**Comment by psuanm5030** [comment] 2017-06-26 17:17
Hmmm... more investigation leads me to the point that this is likely an issue with using node-gyp on windows???  There seems to be many others that are having trouble.  https://github.com/nodejs/node-gyp/issues/629#issuecomment-153196245 

Any thoughts on getting past that?  I followed windows instructions here: https://github.com/nodejs/node-gyp#installation -  which had me install Visual C++ 2015 Build Tools and run a few commands.  Still not working with the same errors.

**Comment by iamEAP** [comment] 2017-06-26 23:42
Hey @psuanm5030, thanks for the detailed report!  Very helpful.

__On Errors__: I was able to reproduce the original error you were seeing on a Mac when using the version of node you have installed.  I've made some updates to the generator that should take care of the issue.  You can update by running `npm install -g generator-web-data-connector`.  You should get `v2.0.0-beta.2`.

__On node-gyp issues__: That's tough. To my knowledge, nothing in the generator itself requires node-gyp. It's possible the WDC simulator requires something that has native needs though.  Maybe give beta.2 a shot and see where you land?

__On an example main.js__: It's a little more complex than what you might do with the Rescuetime API, but you could [look here for inspiration](https://github.com/tableau-mkt/travis-data-connector/blob/2.0/src/main.js).

**Comment by psuanm5030** [comment] 2017-06-27 11:51
Hi @iamEAP - thanks for a quick reply!!!  Your stuff here is great.  This is really fun stuff to learn.  Thanks again.

**On Errors:** I updated the generator, rebuilt and ran grunt and it worked!  Still getting quite a few errors during the npm install & bower install phase - however that bleeds into the next item.... Where there is good news.

**On node-gyp issues:** Looks to do with the contextify node package, however, installing [Visual C++ Build Tools](http://landinghub.visualstudio.com/visual-cpp-build-tools) and python 2.7, then creating a PYTHON path variable seemed to enable it to proceed (I already had anaconda but it apparently wasnt in love with it)!  Finally past that issue - phew!  This is what success looks like: 
![image](https://user-images.githubusercontent.com/10040269/27586059-af61bd9a-5b0c-11e7-8e1e-202eec6b0420.png)

**On the example:** Thanks!!!  It is a learning exercise.  Much appreciated.

**Comment by iamEAP** [comment] 2017-06-27 23:19
Exciting! Any details you can shed (while it's fresh) on running through the install process on Windows would be great additions to the README, if you've got time to contribute back.  No worries if not though.

Closing this out since it looks like we've got resolution, but don't hesitate to reach out with anything else that comes up!

**Closed by iamEAP** 2017-06-27 23:19 UTC
